### ISSUE TITLE
Running on Pi Zero W using Mono

### ISSUE THREAD

**Issue by casper2002casper** [i8beef/HomeAutio.Mqtt.GoogleHome#110]
I only have a RPI zero on hand and would prefer to run it on that, however as .NET core isn't supported it would need to use an alternative implementation. Has someone already tried using mono instead of dotnet or are there any inherent problems?

**Comment by i8beef** [comment]
Pi Zero still doesn't support .NET 5.0 (which Ill be upgrading to shortly) because it depends on instructions not available on the architecture. I haven't done any experimentation on Mono at all, but it looks like some people are playing with it: http://www.codingmatter.com/linux/2018/08/02/Asp-Net-Core-Pi-Zero.html

If you DO try this and get it working, I'd be interested in a writeup of what you did to add to the documentation.

**Comment by casper2002casper** [comment]
I see, in the end I decided to not bother and develop a fulfillment service in Node.js as all my other stuff runs with that. So far I got the oauth stuff working (after a lot of trouble), but lots of work ahead. So this issue can be closed.
