### ISSUE TITLE
Question about UI

### ISSUE THREAD

**Issue by glsf91** [i8beef/HomeAutio.Mqtt.GoogleHome#123]
In the UI there is a header "Default names"  and "Nicknames" but there is no field to add these names.
So why they are there ?
Or why are there no editable fields for it?

**Comment by i8beef** [comment]
They are there because they are part of Google's API. They are disabled because thus far, I haven't found an actual use for them, and its difficult to explain WHICH of the THREE name types you should use, so I just sidestep the confusion by showing they are there, but not letting you use any except the one thats actually required.

If more functionality is built around actually using these in the future, they are easy to enable.

**Comment by glsf91** [comment]
Maybe then also better to make it invisible in the UI. I think it is a little confusion now.

If I use them in the configuration file GoogleDevices.json, will they be used ?
Or is the software skipping them?

**Comment by i8beef** [comment]
The reason I left them is BECAUSE that maintains a parity with the Google device object, so you have a 1:1 to Google's documentation. I.e., its left in on purpose.

If you manually include them in the JSON file they WILL be used, but Im not sure if you are going to overwrite those or not with any subsequent write-backs as you change things in the UI. I think it MIGHT just maintain them, but its untested, FYI.

**Comment by glsf91** [comment]
Clear to me
