### ISSUE TITLE
Stopped working with my girl friend.

### ISSUE THREAD

**Issue by GAZ082** [i8beef/HomeAutio.Mqtt.GoogleHome#21]
Hey there. Used to work with my GF but today stopped. I had to re add the devices as per GH request and that was it, but now just works with me. Don't know if Google made any change.

**Comment by i8beef** [comment]
I don't THINK you should need to do this, rather I suspect its some Google weirdness you're hitting... maybe relinking again would help...

But I do remember at one point last year I had added my wife's Google account that was linked to the Google Home to the permissions screen in the Google Actions site. If you click the gear icon at the top of the menu on the left in the Google Actions page, there's a "permissions" option. This will take you to ANOTHER dashboard that will let you add her email address (My wife is still in my settings as a "Viewer" role and it works for her right now). I'm not sure if this will let the Home use the action AS HER, rather than falling back to the primary linked account (yours) when trying to control devices...

Again, I don't THINK this is necessary anymore, but its something to try. If it works, we can document it.

**Comment by GAZ082** [comment]
Oh yeah, re linked and worked!
