### ISSUE TITLE
Localhost on error

### ISSUE THREAD

**Issue by danielvandenberg95** [i8beef/HomeAutio.Mqtt.GoogleHome#32]
When adding my test project on Android Assistant I get redirected to "http://localhost:5000/home/error?errorId=CfDJ8GF3trMtnQJJq8uQjU-AjSMR5PLvET_buYahjyCFfcHYwm12Hctt67tiQeriD3VQpdPUY3sSAXsrBx3F4QGHN2A9E95nIpnd62QMtgdwKi_XVlCJiGxQ1HeQeD_15Qk6JcZhIuD4yzU3dcKhT-91DFt-wvMaOzMIfjHh8GHN5EEJYwNMyquvZMuMnFXMh-Kq3-qLOOXxoyWK2CVA4sTNrqH1uT8Ggw0x9vB_e6l4-cPcFP3FZAumKsgYHPEy2e4VDnClWCdp4zhMAqxJqC_xEMDGpFK8UnTWujXpJNNCI5iPUGqwPE-8SBnJEsRrH31RKjAHHv3tWNbHDX511VmZaSA" instead of to my public facing url. I don't see "localhost" in my configs anywhere (except for in appsettings.json, which is overridden by appsettings.Production.json). What did I do wrong?

**Comment by i8beef** [comment]
1. How far do you get in the login / linking process?
2. What do you have in the log file around this?

**Comment by shady2k** [comment]
Probably it's incorrect authority and publicOrigin URLs in appsettings.Production.json.

**Comment by danielvandenberg95** [comment]
> Probably it's incorrect authority and publicOrigin URLs in appsettings.Production.json.

This one is set correctly (or at least not to localhost.) However, once I set it to "incorrect:5000" in appsettings.json I get sent to "incorrect" instead of "localhost". If I set it correctly there, it all works.

So now the question is, why doesn't my "publicOrigin" get read from appsettings.Production.json? Other data (like the MQTT settings) do get read properly.



> 1. How far do you get in the login / linking process?
> 2. What do you have in the log file around this?

1. Not far, but as I just figured the error is "unauthorized", which could be correct since I'm not that far with setting it up yet.
2. How can I find those? I'm running docker, but not too familiar with docker.

**Comment by i8beef** [comment]
In your settings file:

1. Is `authority` set to the external URL of the app root? I.e., if hosting at "https://www.blah.com/home" set it to that.
2. Is `publicOrigin` set to the ROOT URL, i.e., for the above location, "https://www.blah.com"?
3. Is your Docker `ASPNETCORE_PATHBASE` environment variable set to the relative URL of the app root? I.e., for above, "/home"

It might also be that you are erroring out earlier than these are setup because the rest of your config isn't complete yet (i.e., its erroring reading the basic config before the actual publicOrigin gets used). Looking at the log would help with that. With the Docker image, the logs will be dumped wherever you mount /app/logs.

**Comment by i8beef** [comment]
Did you get this figured out, or still need this ticket open?

**Comment by CoderFX** [comment]
I'm facing the same problem.
My `ASPNETCORE_PATHBASE `is set to /google/home
Tried this as you instructed
```
"authority": "https://blah.com/google/home/connect/authorize",
"publicOrigin": "https://blah.com/",
"requireSSL": true,
```
but it is not working. I get google error that connection is not private.
