### ISSUE TITLE
Add support for Blinds

### ISSUE THREAD

**Issue by deonp** [i8beef/HomeAutio.Mqtt.GoogleHome#48]
Google have recently added support for blinds
https://developers.google.com/actions/smarthome/guides/blinds

Also:
- Air Freshener
- Dryer
- Fireplace
- Heater

**Comment by i8beef** [comment]
Its on the list. I actually have the new devices added, but am considering how to implement Google's new usage of OpenClose traits since its... different. In the mean time, I do support the beta version of the OpenClose trait which gives you basic open / close for the "Door" type, it just doesnt have the multi-directional support Google has put in.
