### ISSUE TITLE
Maintaining Test mode

### ISSUE THREAD

**Issue by Vayatoalla** [i8beef/HomeAutio.Mqtt.GoogleHome#50]
Hello, great project!

I am developing an IoT project with esp8266 and I have been wandering for several weeks with node-red and / or firebase solutions, but none of them seemed to be able to solve all my needs. Especially the OAuth. And this project seems to resolve everything (hopefully :-))

I'm starting with HomeAutio, but there's one thing on the wiki that bothers me. The section entitled 'Maintain the test mode'. So, this is my question.

If I develop my project with homeAutio.Mqtt.GoogleHome, will it be possible to publish it or is there any restriction that forces it to stay in test mode?

Best regards

**Comment by i8beef** [comment]
There is no such thing as "private" actions with Google Home. The closest we get is keeping one in perpetual "test mode", which is why pretty much every home automation implementation that isn't run by a commercial cloud outfit will take this same approach.

That said, I don't think anyone I know of, at least, is running this project as a Google approved published project, so I don't know if there would be gotchas there, though I don't think there would be (if test mode works, full would too, I just don't think Google would approve your project).

That said, that section of the docs is out of date now and needs removed. Google changed this a while back to allow apps to stay in test mode perpetually.

**Comment by Vayatoalla** [comment]
Nice :-).
Thank you for the answer!.
