### ISSUE TITLE
[Information] Removing expired grants

### ISSUE THREAD

**Issue by Vayatoalla** [i8beef/HomeAutio.Mqtt.GoogleHome#56]
The aplicaction works fine, but I have this log "[Information] Removing expired grants" every minute. Is it normal?

**Comment by i8beef** [comment]
Yes, it's normal. Although arguably doesn't need to be an information level log anymore. There's an embedded OAuth server in the project, and this is where the grants get expired by a background process. Otherwise grants would live forever which would obviously be bad for security.

I'll consider changing this next version bump to at least make the logs less verbose.

**Comment by Vayatoalla** [comment]
OK. Thanks!!
